[profile.default]
src = "src"
out = "out"
script = 'script'
libs = ["lib"]
solc = '0.8.16'
# Disables the optimizer, since gas cost is not a relevant factor.
optimizer = false
evm_version = "shanghai"

fs_permissions = [
    { access = "read", path = "./out/" },
    { access = "read", path = "./script/input/" },
    { access = "read-write", path = "./script/output/" }
]


[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
dspc = "https://virtual.mainnet.rpc.tenderly.co/6182d36e-31c1-4270-aa05-2f6f99fc8861"